spring:
  application:
    name: E-Queue
  data:
    redis:
      host: e-queue-redis
      port: 6379
security:
  oauth2:
    client:
      registration:
        github:
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}