spring:

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  application.name: e-queue

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 0v23Li2NO8woxnQeuIIN
            clientSecret: 99c988b9679a5ccad57146f38bc384e7cad1e7bb